import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
const [playwrightPath,sessionPath,output]=process.argv.slice(2);
const {chromium}=await import(pathToFileURL(playwrightPath).href);
const {preview_url:url}=JSON.parse(fs.readFileSync(sessionPath,'utf8'));
const context=await chromium.launchPersistentContext(path.join(output,'browser-qa-profile'),{channel:'msedge',headless:true,viewport:{width:1440,height:1000}});
const page=context.pages()[0]??await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.goto(url);await page.locator('#image').waitFor({state:'visible',timeout:15000});
await page.screenshot({path:path.join(output,'preview-desktop.png'),fullPage:true});
const before=await (await fetch(url+'state')).json();
await page.setViewportSize({width:800,height:1000});
await page.screenshot({path:path.join(output,'preview-narrow.png'),fullPage:true});
await context.close();
await new Promise(r=>setTimeout(r,2500));
const after=await (await fetch(url+'state')).json();
const report={errors,before_frames:before.video.frames,after_frames:after.video.frames,continued_without_viewer:after.video.frames>before.video.frames+5,node_rss_mib:after.memory_mib,frame_age_ms:after.video.age_ms};
fs.writeFileSync(path.join(output,'preview-qa.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
if(errors.length||!report.continued_without_viewer)process.exitCode=1;
